import java.io.FileInputStream
import java.util.Properties

plugins {
    // Plugins automatically generated by MLGradleWriter.kt
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)

    alias(libs.plugins.ksp)
}

// 固定发布签名：从根目录 keystore.properties 读取（该文件与 keystore 均已 gitignore，不进公开仓库）。
// 只要 keystore 文件不变，签名（SHA-256 指纹）就永久固定，升级可原地覆盖安装。
val keystorePropsFile = rootProject.file("keystore.properties")
val keystoreProps = Properties()
if (keystorePropsFile.exists()) {
    FileInputStream(keystorePropsFile).use { keystoreProps.load(it) }
}

android {
    namespace = "com.yunget.app"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.yunget.app"
        minSdk = 23
        targetSdk = 34
        versionCode = 17
        versionName = "2.6.4"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        if (keystoreProps.isNotEmpty()) {
            create("release") {
                storeFile = rootProject.file(keystoreProps.getProperty("storeFile"))
                storePassword = keystoreProps.getProperty("storePassword")
                keyAlias = keystoreProps.getProperty("keyAlias")
                keyPassword = keystoreProps.getProperty("keyPassword")
                // 同时启用 V1/V2/V3 签名方案，兼容各 Android 版本
                enableV1Signing = true
                enableV2Signing = true
                enableV3Signing = true
            }
        }
    }

    buildFeatures {
        compose = true
    }

    buildTypes {
        release {
            // 有 keystore 配置时使用固定发布签名；否则回退默认（仅本机调试）
            signingConfig = signingConfigs.findByName("release")
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("17"))
        }
    }
}

/**
 * 【防"陈旧产物"事故】校验 release APK **内嵌**的 versionCode/versionName
 * 是否与当前 `build.gradle.kts` 一致。
 *
 * 起因（真实事故）：构建**跑着的时候**才去改版本号 →
 * 打出来的 APK 是旧版本（2.6.0 / code 13），却按新版本号（2.6.1 / code 14）发了出去。
 * 用户装上去看到的版本号是旧的，而且**从产物上完全看不出来**。
 *
 * Gradle 无法阻止"先构建、后改版本"，但可以在**发布前**把这种不一致拦住。
 * 发版流程应改为：改版本号 → `assembleRelease` → **`verifyApkVersion`** → 上传。
 */
tasks.register("verifyApkVersion") {
    group = "verification"
    description = "校验 release APK 内嵌版本与 build.gradle.kts 一致（发版前置检查）"
    dependsOn("assembleRelease")

    doLast {
        val apk = layout.buildDirectory.file("outputs/apk/release/app-release.apk").get().asFile
        if (!apk.isFile) throw GradleException("未找到 release APK：$apk")

        val expectedName = android.defaultConfig.versionName
        val expectedCode = android.defaultConfig.versionCode
        if (expectedName == null || expectedCode == null) {
            throw GradleException("android.defaultConfig 未设置 versionName/versionCode")
        }

        // 从 local.properties / 环境变量定位 Android SDK
        // 注意：这里**不能**写 `java.util.Properties()` —— Kotlin DSL 里 `java` 是 Gradle 的
        // JavaPluginExtension，会遮蔽同名包。文件顶部已 `import java.util.Properties`，直接用即可。
        val props = Properties()
        sequenceOf(rootProject.file("local.properties"), project.file("local.properties"))
            .firstOrNull { it.isFile }
            ?.inputStream()?.use { props.load(it) }
        val sdkDir = props.getProperty("sdk.dir")
            ?: System.getenv("ANDROID_HOME")
            ?: System.getenv("ANDROID_SDK_ROOT")
            ?: throw GradleException("找不到 Android SDK（local.properties 的 sdk.dir 或 ANDROID_HOME）")

        val aapt2 = File(sdkDir, "build-tools")
            .listFiles()?.sortedByDescending { it.name }
            ?.asSequence()
            ?.map { File(it, "aapt2.exe").takeIf { f -> f.isFile } ?: File(it, "aapt2") }
            ?.firstOrNull { it.isFile }
            ?: throw GradleException("在 $sdkDir/build-tools 下找不到 aapt2")

        val badging = providers.exec {
            commandLine(aapt2.absolutePath, "dump", "badging", apk.absolutePath)
        }.standardOutput.asText.get()

        val m = Regex("versionCode='(\\d+)' versionName='([^']*)'").find(badging)
            ?: throw GradleException("无法从 APK 解析版本信息：$apk")
        val actualCode = m.groupValues[1].toInt()
        val actualName = m.groupValues[2]

        if (actualCode != expectedCode || actualName != expectedName) {
            throw GradleException(
                buildString {
                    appendLine("APK 内嵌版本与源码不一致 —— 产物是**陈旧**的，绝不能发布！")
                    appendLine("    APK  : versionCode=$actualCode versionName=$actualName")
                    appendLine("    源码 : versionCode=$expectedCode versionName=$expectedName")
                    appendLine("处理：确认版本号改动已完成，然后重新执行 assembleRelease（不要复用旧产物）。")
                }
            )
        }
        logger.lifecycle("verifyApkVersion OK: versionCode=$expectedCode versionName=$expectedName")
    }
}

dependencies {
    implementation("androidx.compose.material:material-icons-extended")
    implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.7")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.8.7")
    implementation("com.squareup.okhttp3:okhttp:4.12.0")

    // TurboDL SDK（纯 JVM 多线程下载引擎 + 可选插件框架），从 mavenLocal 解析 dev.turbodl:*:0.2.0-rc16
    implementation("dev.turbodl:turbodl-core:0.2.0-rc18")
    implementation("dev.turbodl:turbo-plugin-runtime:0.2.0-rc18")
    implementation("dev.turbodl:turbo-plugin-bootstrap:0.2.0-rc18")
    implementation("dev.turbodl:turbo-plugin-hls:0.2.0-rc18")

    implementation(libs.material)   // 原 libs.material.color.utilities -> 改为官方 Material 主库（含 color.utilities 包）

    implementation(libs.room.runtime)
    implementation(libs.room.ktx)          // 提供协程扩展，如 Flow、suspend
    ksp(libs.room.compiler)

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.ui)
    implementation(libs.androidx.ui.graphics)
    implementation(libs.androidx.ui.tooling.preview)
    implementation(libs.androidx.material3)
    testImplementation("junit:junit:4.13.2")
    debugImplementation(libs.androidx.ui.tooling)
    debugImplementation(libs.androidx.ui.test.manifest)
}
