import java.io.FileInputStream
import java.util.Properties

plugins {
    // Plugins automatically generated by MLGradleWriter.kt
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)

    alias(libs.plugins.ksp)
}

// 固定发布签名：从根目录 keystore.properties 读取（该文件与 keystore 均已 gitignore，不进公开仓库）。
// 只要 keystore 文件不变，签名（SHA-256 指纹）就永久固定，升级可原地覆盖安装。
val keystorePropsFile = rootProject.file("keystore.properties")
val keystoreProps = Properties()
if (keystorePropsFile.exists()) {
    FileInputStream(keystorePropsFile).use { keystoreProps.load(it) }
}

android {
    namespace = "com.yunget.app"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.yunget.app"
        minSdk = 23
        targetSdk = 34
        versionCode = 47
        // 2.6.22 内容：**修「暂停/继续时进度数字前后跳」**
        //  ① 现象（用户实报）：暂停显示 29.2 MB，点继续变 24.5 MB；另一次是暂停 9.2 MB、继续变 24.8 MB，
        //     看着像"进度倒退、断点续传没生效"。**实际上两次都在接着下** —— 设备日志写得很清楚：
        //     `resume=[parts=true weak=false changed=false print=NOT_ATTEMPTED discard=false]`（分片全保留）、
        //     `首字节 … downloaded=24767785`（引擎从磁盘上的 24.8 MB 起步），任务随后完整下到 221.1 MB。
        //  ② 根因：列表上的「已下载」读的是**库里的值**，而库是按 800ms 节流写的。正常下载时它落后
        //     真实进度若干 MB（下一个节拍就补上，无害）；但**暂停后再也收不到进度事件**，那个落后值
        //     就被永久冻在列表上。继续时引擎从磁盘真实字节起步上报，数字当场跳到真实值 —— 于是
        //     前后两个数字来自两个口径，看起来就是"倒退"。
        //  ③ 修法：把暂停当成状态切换点，补写一次库。取值优先用引擎的**实时计数器**（逐块更新，
        //     比最近一次上报事件更新），其次内存里最近的上报值，最后上次写库值；总大小缺失时回读
        //     库里的原值，避免把「/ 221.1 MB」写成「/ 0 B」。完成/失败/未授权三条收尾路径一并
        //     清掉该任务的内存态。
        // 2.6.21 内容：**修 2.6.19 起就存在的第二个蓝奏故障**（与 2.6.20 修的是同一链路上的两处）
        //  ① 「缺少下载参数」与「下载地址循环跳转」是**两个独立的缺陷**，前者在 2.6.20 修掉了，
        //     修好之后流程第一次真正走到下载节点，第二个才暴露出来（此前它被前一个错误挡在前面）。
        //  ② 循环跳转的根因：命中 acw_sc__v2 人机校验页时，代码会算出 Cookie 后**重放同一个地址**
        //     —— 那是设计好的第二次请求。而循环检测只按 URL 去重，于是这次重放必然被判成
        //     「循环跳转」，这条重放路径实际上从来没成功过。现在连着当时发出去的 Cookie 一起记：
        //     Cookie 变了 = 新尝试，没变 = 真循环（真正的 A→B→A 仍然会被抓到）。
        //  ③ 顺手给这条链路补了诊断日志（logcat，随「导出日志」一起回传）：每跳的 host/path/状态码、
        //     命中校验页、提交验证、参数取自哪一份 HTML。只记 host+path 不记 query ——
        //     蓝奏直链的 query 带签名，等于临时钥匙，不该写进要发给别人看的日志里。
        //     前两个故障来回猜了好几轮，就是因为它"请求了哪一页"完全看不见。
        //  ④ 引擎跟进到 **TurboDL 0.2.0.6**：运行时补齐了 loadSource / 归属级联 / 并发卸载语义，
        //     HLS 插件与引擎行为本身不变。四个坐标（core / runtime / bootstrap / hls）一起跟上，
        //     顺带把文档与官网里写着 0.2.0.5 的地方全部改成 0.2.0.6。
        // 2.6.20 内容：
        //  ① **修复蓝奏分享点文件报「缺少下载参数」**，三条根因：
        //     - 文件夹分享的分享页是**目录页**，上面没有下载参数 —— 参数在文件夹里每个文件
        //       自己的页面上（`{host}/{文件key}`）。以前直接拿目录页去找 sign，必然落空；
        //       现在按协议的走法先取文件自己的页面。
        //     - `absolutize()` 处理不了协议相对地址（iframe src 常写成 `//host/path`），
        //       会拼出 `https://host//host/path` 这种双主机地址，请求必然失败。
        //     - 参数名不再硬编码：新版页面把参数写成对象且值是变量名
        //       （`data: {'action':'downprocess','sign':wp_sign}`），现在整体解析后再回查变量。
        //     - 顺手补上子目录：它们只在分享页 HTML 上、以前被当成文件，点进去同样报缺参数。
        //       子目录现在能进入（分页参数从子目录自己的页面重新解析）。
        //  ② **引擎入口合并到一处**：原来「下载引擎」页只选「内置 / Gopeed」，具体实现
        //     （TurboDL / 内置兼容 / aria2）在设置页的另一个弹窗里。现在四套引擎都在
        //     「下载引擎」页上选，aria2 可用性检测也一起搬过去。
        //  ③ 该页补一句实话：网盘直链要带 Cookie / Referer 才下得动，只有 TurboDL 走这条路径，
        //     aria2 与内置兼容引擎下网盘基本不可用，Gopeed 面向磁力 / BT。
        // 2.6.18 内容（**紧急修复**：2.6.17 升级用户启动即崩）：
        //  ① **修复数据库迁移与实体不一致导致的启动崩溃**：
        //     2.6.17 为了对齐上游版本号，在迁移里补了两列 —— `download_task.avgSpeed`
        //     与 `xunlei_account.authType`，但**忘了把这两个字段加进对应的 Entity**。
        //     Room 在迁移后会校验表结构，发现库里多出一列就抛
        //     `IllegalStateException: Migration didn't properly handle` ——
        //     **所有从旧版本升级上来的用户，打开应用立刻崩溃**
        //     （开发机是新装库、走建表路径不经迁移，所以本地测不出来）。
        //     现已给两个实体补上同名字段（默认值与迁移的 DEFAULT 一致）。
        //  ② **新增迁移契约测试**（`DatabaseMigrationContractTest`）：
        //     直接从源码解析迁移 SQL 与实体字段并双向比对，钉死三类疏漏 ——
        //     迁移加了列但实体没声明（本次事故）、建表列与实体字段不一致、
        //     迁移链断裂或未注册。已验证该测试在事故代码上**必定失败**。
        //  ③ 该测试同时替代了原先手抄 SQL 的旧版契约测试（抄一份的话，
        //     「改迁移忘改测试」与「改迁移忘改实体」是同一类错误，测试会跟着一起错）。
        //
        // 2.6.17 内容（全量同步上游 YunX 一周的更新：4 个新网盘 + 新下载引擎 + 一批修复）：
        //  ① **新增 4 个网盘**：115 网盘、光鸭云盘、蓝奏云优享版、蓝奏云。
        //     每个平台含登录（部分为网页登录/账号密码登录）、云盘管理、分享解析、
        //     转存、下载全链路；凭证同样走 Keystore 加密（数据库 v11→v19，含 4 张新表）。
        //  ② **内置 Gopeed 下载引擎**（可选，需在「设置 → 下载引擎」导入内核）：
        //     支持磁力/BT 这类内置分片下载器做不到的任务；引擎内核从 Release 下载后
        //     运行时导入（不进 APK，避免安装包膨胀 56MB）。与内置下载器可切换。
        //  ③ **磁力链接支持**：解析 magnet 链接的显示名与 info hash，交由 Gopeed 引擎执行。
        //  ④ **迅雷中文口令**：粘贴如「张三丰资源」这类口令，自动换成带提取码的分享链接。
        //  ⑤ **修复分享有效期错位**（上游 #127）：139/百度/123 三个平台此前把界面的
        //     中性码（1/2/3/4）当成天数直接下发，导致「选永久建成 1 天」「选 7 天建成 3 天」。
        //     现在统一经 ShareExpire 转换，未知码位直接抛错（宁可报错也不建错分享）。
        //  ⑥ **修复下载目录选择器崩溃**（上游 #122）：系统文件选择器被卸载/冻结时
        //     点击即崩溃，现在给出可读提示。
        //  ⑦ **文件删除支持目录**、**内存压力回收空闲连接**、**Room 的 R8 保留规则**、
        //     **Android 16 实时更新权限**（详见 2.6.16 段）。
        //  ⑧ 认证备份扩展到这 10 个平台；分享链接解析新增蓝奏系的域名族识别与
        //     115 口令形式（含「ilanzou 不能被误判为 lanzou」的顺序保护）。
        //
        // 2.6.16 内容（同步上游 YunX v1.2.9 的稳定性与安全修复）：
        //  ① **修复「改锁屏密码后 App 崩溃」**（同步上游 v1.2.9，上游收到 3 份崩溃报告）：
        //     Android Keystore 里的密钥会被系统**永久作废**（改锁屏密码/指纹、系统升级、
        //     部分机型的 keyblob 升级路径），此时 `key()` 抛出的裸 Keystore 异常
        //     （InvalidKeyException / KeyPermanentlyInvalidatedException / Invalid key blob）
        //     会直接击穿主线程。现在三级处理：条目坏了 → 删坏条目 + 建新密钥 + **同一段
        //     加解密流程重试一次**；条目只是暂时取不到（设备未解锁）→ 抛 Unavailable，
        //     **绝不删键**；重试仍失败 → 抛 PermanentlyInvalid，由数据层清残留。
        //  ② **修复「凭证被误删」**：数据层原先对所有解密异常一律 `clear()`，
        //     于是「设备刚重启还没解锁」这种**暂时**取不到密钥的情况也会清掉凭证 ——
        //     用户下次解锁后莫名要求重登。现在只有「永久失效」才清，暂时不可用不动数据。
        //  ③ **新增密钥失效提示**：凭证真的失效时弹一次对话框说明原因（此前是"账号莫名没了"）。
        //  ④ `observeAccount()` 的 Flow 补 `.catch`：否则数据库变更流里的解密异常
        //     会直接取消收集者，表现为网盘页静默无数据。
        //  ⑤ **内存压力回收**（`onTrimMemory`）：系统内存吃紧时释放空闲 HTTP 连接
        //     及其 socket / TLS 缓冲（下载数据全部流式落盘、不在堆上缓存，不影响进行中的下载）。
        //  ⑥ 删除本地文件时支持目录（`File.delete()` 对非空目录必然失败），
        //     此前用户勾了「同时删除本地文件」可能是什么都没删掉。
        //  ⑦ 补 Room 的 R8 保留规则（当前 release 未开混淆，属预先对齐，避免将来开混淆
        //     后出现「表存在但字段找不到」这类只在 release 版复现的崩溃）。
        //  ⑧ 补 Android 16 实时更新权限（POST_PROMOTED_NOTIFICATIONS），
        //     下载进度可进入状态栏实时进度区域（OPPO ColorOS 流体云按此规范接入）。
        //
        // 2.6.15 内容（修复开发诊断功能不可用）：
        //  ① **修复诊断报「指定的链接不可用： NetworkOnMainThreadException」**：
        //     诊断前的预检探活是阻塞网络调用，却被主线程协程直接调用 —— Android 禁止
        //     主线程发网络请求，异常被 catch 后伪装成"链接不可用"，与真实链接好坏无关，
        //     用户会误以为链接失效。现改为挂起版探活（内部强制切 IO 线程），
        //     三处诊断调用点全部改用，扫描过程中的两处探活同步切 IO。
        //  ② **诊断按钮不再静默吞异常**：原先 `runCatching { ... }` 把启动阶段的任何
        //     异常无声丢弃，用户只看到"什么都没发生"。现在失败原因会以 Snackbar 弹出。
        //  ③ 引擎 0.2.0.4：探活前先做**出站地址预检**（非 http/https、环回/内网/
        //     链路本地/组播地址直接拒绝并给出可读原因），不再发起注定失败的网络请求。
        //
        // 2.6.14 内容（DNS 自动择优 + 诊断可用性修复）：
        //  ① DNS 自动模式：新增「自动」选项 —— 并发探测多个公共 DoH，采用最快给出
        //     有效结果的端点并在之后固定复用；全部失败回退系统 DNS。
        //     此前用户只能在「系统 DNS」与「手填一个 DoH」之间二选一，而实测国内网络下
        //     境外 DoH（Google/Cloudflare）完全不可达、境内 DoH 可用 —— 用户往往先填
        //     境外那几个，结果"开了 DoH 反而更慢"。设置页同时提供各端点延迟可视化，
        //     一眼看出当前网络下哪个可用。仅首次解析探测一次（结果缓存 5 分钟），
        //     **不影响正常连接速度**。
        //  ② 修复诊断功能不可用：诊断需要一条当前可用的直链，而任务表存的是取链时刻的
        //     签名直链（网盘直链短时有效，如夸克约 3 小时；分享转存类任务下载完还会
        //     删掉云端临时目录使其永久失效）。旧任务全部过期后诊断只报"没有链接可用的
        //     任务"。现在候选改为**最新任务优先**，并新增「诊断用直链」输入框，
        //     可粘贴一条新链接直接测。
        //
        // 2.6.12 内容（继续同步上游：收藏功能、登录态修复、进度写库节流修正）：
        //  ① **网盘链接收藏**（取自上游 #71）：解析页标题栏新增入口，
        //     可保存分享链接/提取码并按分类管理，点击条目直接回到解析页开始解析。
        //     新增 Room 表 bookmark（DB 版本 10→11，带迁移）。
        //  ② **修复「登录后网盘页仍显示请先登录」**（取自上游 #78 的第三项）：
        //     6 个云盘浏览 VM 原先在 init 中无条件 loadRoot()，未登录时置为错误态，
        //     而登录成功后没有任何机制触发重载 —— 用户必须手动点「重试」。
        //     现改为监听登录态，登录成功自动重载（drop(1) 跳过冷启动快照避免重复请求）。
        //  ③ **修复进度写库节流**：原按「800ms 或增长 1MB」双条件，高速下载下
        //     1MB 阈值先触发 → 每秒写库约 50 次 → 每次触发全表 Flow 重发 →
        //     主线程反复重组下载列表（ANR 成因，即上游 #64 报告的问题）。
        //     改为**纯时间节流**，写库频率恒定约 1.25 次/秒，与下载速度无关。
        //     同时修正并发竞态：多 worker 同时进入节流判断会重复写库，
        //     改用 CAS 占位；并修正首次写入（replace 对不存在的键返回 false 会导致永不写库）。
        //
        // 2.6.11 内容（同步上游 YunX 的安全加固与 UI 升级）：
        //  ① **凭证加密**（取自上游 PR #53）：各网盘 cookie / accessToken 此前**明文存库**，
        //     现改为 AES-GCM + Android Keystore 加密（密钥不可导出，AAD 绑定用途）。
        //     读取时解密且放在 IO 线程（Keystore 是 Binder IPC，单次 30~75ms，
        //     主线程解密会让网盘页并发刷新时整应用掉帧）。
        //     老数据平滑迁移：读到明文自动加密回写，无需重新登录；
        //     解密失败则清空该条凭证（宁可重登，也不留无法使用的脏数据）。
        //  ② **日志脱敏**（LogRedactor）：URL 只保留 scheme+host，
        //     抹掉 cookie / token / 签名参数后再写入日志与导出文件。
        //  ③ **保存阶段流式落盘**（取自上游 #100）：DownloadSaver 直接向最终位置写入，
        //     不再经过私有缓存副本，峰值存储占用从 3 份降到约 1 份，
        //     并修复保存阶段 ENOSPC 与「文件已删但任务仍在」的幽灵任务。
        //     新增 DownloadPathPolicy 做**路径穿越防护**（拒绝 .. 与绝对路径）。
        //  ④ **Material 3 Expressive UI**（取自上游 #103）：material3 升到 1.5.0-alpha18，
        //     全局动效改为弹簧物理规格（位移用 spatial / 透明度用 effects），
        //     加载指示器统一为 Expressive 波浪形变（替换 40 处圆形进度圈）。
        //  ⑤ 51 个文件补上 **AGPL-3.0 许可证头**（此前缺失，属合规缺口）。
        //  ⑥ 版本比较与更新检测修复（同 2.6.10，见下）。
        //
        // 2.6.10 内容（引擎调度与合并提速 + 更新检测修复）：
        //  ① **修「检查更新」看不到测试版**：原先用 GitHub 的 `/releases/latest`，
        //     该接口**按设计跳过预发布版**，于是装了 2.6.9 反而提示"已是最新"
        //     （线上"最新"返回的是 2.6.7）。改用 releases 列表 + 按版本号取最大，
        //     并支持 `-devN` / `-rcN` 后缀比较（dev9 < dev12，且 dev 版 < 同号正式版）。
        //  ② 引擎升级到 TurboDL rc24：
        //     - 慢启动改为「时间节拍 + 分片完成」双触发。原先爬升挂在"每 N 个分片成功"上，
        //       而分片时长 = 块大小/速率 → **块越大爬得越慢**，最需要并发的场景最慢。
        //       实测网络段 6.01s → 4.57s（512MB/16连接/每连接 8MB/s）。
        //     - 合并改并行：MERGING 段原先只有 126 MB/s（刚下完时页缓存全是脏页，
        //       单线程顺序合并在等回写），改为预分配 + 多线程按偏移直写。
        //       实测 3.8s → 0.27~1.58s。
        //     - 收尾托管（tail assist）：只在「队列空 + 有空闲 worker」时把在飞分片的
        //       后半段让给空闲连接（思路来自 aria2-next 的 rebalanceEndgame）。
        //     - 分片请求带 `If-Range`：防止 CDN 中途换文件时新旧字节拼出混杂文件
        //       （那种情况长度校验会通过，损坏会静默落地）。
        //     - 401/403/410 不再触发背压降并发（是授权/时效信号，不是"你太快了"）。
        versionName = "2.6.22"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        if (keystoreProps.isNotEmpty()) {
            create("release") {
                storeFile = rootProject.file(keystoreProps.getProperty("storeFile"))
                storePassword = keystoreProps.getProperty("storePassword")
                keyAlias = keystoreProps.getProperty("keyAlias")
                keyPassword = keystoreProps.getProperty("keyPassword")
                // 同时启用 V1/V2/V3 签名方案，兼容各 Android 版本
                enableV1Signing = true
                enableV2Signing = true
                enableV3Signing = true
            }
        }
    }

    buildFeatures {
        compose = true
    }

    packaging {
        jniLibs {
            /**
             * 必须为 true，否则 `jniLibs` 里的 aria2c 无法执行。
             *
             * AGP 8.x 默认 `useLegacyPackaging = false`（等价 `extractNativeLibs=false`）：
             * .so 不落盘，以未压缩页对齐形式留在 APK 内由 linker 直接从 APK 加载。
             * 后果是 `applicationInfo.nativeLibraryDir` 目录里**没有文件** →
             * `Runtime.exec()` 必然 `ENOENT`，aria2 引擎永远起不来。
             *
             * 置 true 后安装时会把这些库解压到 nativeLibraryDir（应用可执行），
             * 代价是安装后多占一份磁盘（arm64 的 aria2c 约 6MB）。
             * 这是"APK 内自带可执行文件"路线的硬前提，不是可选优化。
             */
            useLegacyPackaging = true
        }
    }

    buildTypes {
        release {
            // 有 keystore 配置时使用固定发布签名；否则回退默认（仅本机调试）
            signingConfig = signingConfigs.findByName("release")
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("17"))
        }
    }
}

/**
 * 【防"陈旧产物"事故】校验 release APK **内嵌**的 versionCode/versionName
 * 是否与当前 `build.gradle.kts` 一致。
 *
 * 起因（真实事故）：构建**跑着的时候**才去改版本号 →
 * 打出来的 APK 是旧版本（2.6.0 / code 13），却按新版本号（2.6.1 / code 14）发了出去。
 * 用户装上去看到的版本号是旧的，而且**从产物上完全看不出来**。
 *
 * Gradle 无法阻止"先构建、后改版本"，但可以在**发布前**把这种不一致拦住。
 * 发版流程应改为：改版本号 → `assembleRelease` → **`verifyApkVersion`** → 上传。
 */
tasks.register("verifyApkVersion") {
    group = "verification"
    description = "校验 release APK 内嵌版本与 build.gradle.kts 一致（发版前置检查）"
    dependsOn("assembleRelease")

    doLast {
        val apk = layout.buildDirectory.file("outputs/apk/release/app-release.apk").get().asFile
        if (!apk.isFile) throw GradleException("未找到 release APK：$apk")

        val expectedName = android.defaultConfig.versionName
        val expectedCode = android.defaultConfig.versionCode
        if (expectedName == null || expectedCode == null) {
            throw GradleException("android.defaultConfig 未设置 versionName/versionCode")
        }

        // 从 local.properties / 环境变量定位 Android SDK
        // 注意：这里**不能**写 `java.util.Properties()` —— Kotlin DSL 里 `java` 是 Gradle 的
        // JavaPluginExtension，会遮蔽同名包。文件顶部已 `import java.util.Properties`，直接用即可。
        val props = Properties()
        sequenceOf(rootProject.file("local.properties"), project.file("local.properties"))
            .firstOrNull { it.isFile }
            ?.inputStream()?.use { props.load(it) }
        val sdkDir = props.getProperty("sdk.dir")
            ?: System.getenv("ANDROID_HOME")
            ?: System.getenv("ANDROID_SDK_ROOT")
            ?: throw GradleException("找不到 Android SDK（local.properties 的 sdk.dir 或 ANDROID_HOME）")

        val aapt2 = File(sdkDir, "build-tools")
            .listFiles()?.sortedByDescending { it.name }
            ?.asSequence()
            ?.map { File(it, "aapt2.exe").takeIf { f -> f.isFile } ?: File(it, "aapt2") }
            ?.firstOrNull { it.isFile }
            ?: throw GradleException("在 $sdkDir/build-tools 下找不到 aapt2")

        val badging = providers.exec {
            commandLine(aapt2.absolutePath, "dump", "badging", apk.absolutePath)
        }.standardOutput.asText.get()

        val m = Regex("versionCode='(\\d+)' versionName='([^']*)'").find(badging)
            ?: throw GradleException("无法从 APK 解析版本信息：$apk")
        val actualCode = m.groupValues[1].toInt()
        val actualName = m.groupValues[2]

        if (actualCode != expectedCode || actualName != expectedName) {
            throw GradleException(
                buildString {
                    appendLine("APK 内嵌版本与源码不一致 —— 产物是**陈旧**的，绝不能发布！")
                    appendLine("    APK  : versionCode=$actualCode versionName=$actualName")
                    appendLine("    源码 : versionCode=$expectedCode versionName=$expectedName")
                    appendLine("处理：确认版本号改动已完成，然后重新执行 assembleRelease（不要复用旧产物）。")
                }
            )
        }
        logger.lifecycle("verifyApkVersion OK: versionCode=$expectedCode versionName=$expectedName")
    }
}

dependencies {
    implementation("androidx.compose.material:material-icons-extended")
    implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.7")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.8.7")
    implementation("com.squareup.okhttp3:okhttp:4.12.0")

    // TurboDL SDK（纯 JVM 多线程下载引擎 + 可选插件框架），从 mavenLocal 解析 dev.turbodl:*:0.2.0.6
    implementation("dev.turbodl:turbodl-core:0.2.0.6")
    implementation("dev.turbodl:turbo-plugin-runtime:0.2.0.6")
    implementation("dev.turbodl:turbo-plugin-bootstrap:0.2.0.6")
    implementation("dev.turbodl:turbo-plugin-hls:0.2.0.6")

    implementation(libs.material)   // 原 libs.material.color.utilities -> 改为官方 Material 主库（含 color.utilities 包）

    // Gopeed 内置下载引擎：gomobile 生成的 Java 桥接类（com/gopeed/libgopeed + go，合计 12 KB），
    // 只为编译期拿到 Libgopeed / InvokeResultListener 等类型定义；真正的引擎
    // libgojni.so（约 56 MB）不进仓库、不进 APK，由设置页导入 AAR 后运行时解出并 System.load。
    // 来源：libgopeed-arm64-v8a.aar 内的 classes.jar（原样拷贝，未做任何修改）。
    implementation(files("libs/gopeed-classes.jar"))

    implementation(libs.room.runtime)
    implementation(libs.room.ktx)          // 提供协程扩展，如 Flow、suspend
    ksp(libs.room.compiler)

    // GitHub README 的 GFM 渲染（表格/嵌套列表/代码高亮/图片）
    implementation(libs.markdown.renderer)

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.ui)
    implementation(libs.androidx.ui.graphics)
    implementation(libs.androidx.ui.tooling.preview)
    implementation(libs.androidx.material3)
    testImplementation("junit:junit:4.13.2")
    debugImplementation(libs.androidx.ui.tooling)
    debugImplementation(libs.androidx.ui.test.manifest)
}
